// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"log/slog"
	"net/http"

	"application/config"
	"application/internal/v1/biz/healthz"
	"application/internal/v1/datasource/healthz/memory"
	koanf2 "application/internal/v1/datasource/rule/koanf"
	http2 "application/internal/v1/http"
	"application/internal/v1/http/handler"
	"github.com/coreos/go-oidc/v3/oidc"
	"github.com/knadh/koanf/v2"
	"golang.org/x/oauth2"
)

// Injectors from wire.go:

func wireApp(ctx context.Context, cfg config.Config, logger *slog.Logger, k *koanf.Koanf, oauthConfig *oauth2.Config, oauthVerifier *oidc.IDTokenVerifier, security *config.Security, httpConfig *config.HTTPServer) (http.Handler, error) {
	healthzRepoInterface := memory.NewHealthzDS(logger)
	healthzUseCaseInterface := biz.NewHealthzBiz(healthzRepoInterface, logger)
	healthzHandler := handler.NewMuxHealthzHandler(healthzUseCaseInterface, logger, httpConfig)
	rule := koanf2.NewRuleDS(k)
	oAuthHandler := handler.NewOauthHandler(logger, rule, oauthConfig, oauthVerifier, security, httpConfig)
	v := handler.NewHandlerList(healthzHandler, oAuthHandler)
	httpHandler := http2.NewHTTPHandler(v...)
	return httpHandler, nil
}
