// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"git.abanppc.com/farin-project/event/config"
	"git.abanppc.com/farin-project/event/domain/biz/event"
	mongo2 "git.abanppc.com/farin-project/event/domain/repository/v1/event/mongo"
	"git.abanppc.com/farin-project/event/internal/rabbit/consumers"
	"git.abanppc.com/farin-project/event/pkg/mongo"
	"git.abanppc.com/farin-project/event/pkg/rabbit"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(logger *slog.Logger, cfg *config.Config, rbt *rabbit.Rabbit, rbtConfig *config.RabbitMQ, mongo3 *mongo.Mongo) (*Bootstrap, error) {
	eventRepository := mongo2.NewEventRepository(mongo3)
	eventBizInterface := event.NewEventBiz(eventRepository, logger)
	v := consumers.Consumers(logger, rbt, rbtConfig, eventBizInterface)
	bootstrap := NewBootstrap(rbtConfig, v...)
	return bootstrap, nil
}
