apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vehicle-record-resources
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git.abanppc.com/farin-project/infra/argocd.git
    targetRevision: HEAD
    path: resources/uat/vehicle-record
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
