// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/mahdimehrabi",
            "email": "mahdimehrabi17@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/idp/v1/users": {
            "get": {
                "description": "List of users IDP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IDP",
                    "User"
                ],
                "summary": "List of users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/application_internal_http_dto.UserListResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create User IDP",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IDP",
                    "User"
                ],
                "summary": "Create User",
                "parameters": [
                    {
                        "description": "request body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/application_internal_http_dto.UserCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/application_internal_http_dto.UserCreateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "application_internal_http_dto.User": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "email_verfied": {
                    "type": "boolean"
                },
                "msisdn": {
                    "type": "string"
                },
                "msisdn_verfied": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "application_internal_http_dto.UserCreateRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "email_verfied": {
                    "type": "boolean"
                },
                "msisdn": {
                    "type": "string"
                },
                "msisdn_verfied": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "application_internal_http_dto.UserCreateResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "email_verfied": {
                    "type": "boolean"
                },
                "msisdn": {
                    "type": "string"
                },
                "msisdn_verfied": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "application_internal_http_dto.UserListResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/application_internal_http_dto.User"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Boilerplate",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
