// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"git.abanppc.com/farin-project/state/app/api/controllers"
	"git.abanppc.com/farin-project/state/app/api/routes"
	rabbit2 "git.abanppc.com/farin-project/state/app/rabbit"
	"git.abanppc.com/farin-project/state/app/rabbit/consumers"
	"git.abanppc.com/farin-project/state/app/rabbit/handlers"
	"git.abanppc.com/farin-project/state/domain/repository"
	"git.abanppc.com/farin-project/state/domain/service"
	"git.abanppc.com/farin-project/state/infrastructure/godotenv"
	"git.abanppc.com/farin-project/state/infrastructure/gorm"
	"git.abanppc.com/farin-project/state/infrastructure/rabbit"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(logger *slog.Logger, rabbit3 *rabbit.Rabbit, gorm *gormdb.GORMDB) (*Boot, error) {
	stateRepository := repository.NewStateRepository(gorm)
	env := godotenv.NewEnv()
	stateService := service.NewStateService(logger, stateRepository, env)
	state := handlers.NewState(logger, stateService)
	stateConsumer := consumers.NewEventConsumer(logger, env)
	v := rabbit2.Consumers(stateConsumer)
	consumerRunner := rabbit.NewConsumerRunner(logger, v...)
	healthController := controller.NewHealthController(logger, rabbit3, gorm, stateConsumer)
	healthRouter := routes.NewHealthRouter(healthController)
	v2 := routes.CreateRouters(healthRouter)
	boot := NewBoot(state, stateConsumer, rabbit3, consumerRunner, v2...)
	return boot, nil
}
