// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/vehicle-records/{id}": {
            "get": {
                "description": "Retrieve vehicleRecord details by ID",
                "tags": [
                    "vehicleRecords"
                ],
                "summary": "Get vehicleRecord details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "VehicleRecord ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/git_abanppc_com_farin-project_vehicle-records_app_api_response.Response-git_abanppc_com_farin-project_vehicle-records_domain_entity_VehicleRecord"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/git_abanppc_com_farin-project_vehicle-records_app_api_response.Response-swagger_EmptyObject"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/git_abanppc_com_farin-project_vehicle-records_app_api_response.Response-swagger_EmptyObject"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "git_abanppc_com_farin-project_vehicle-records_app_api_response.Response-git_abanppc_com_farin-project_vehicle-records_domain_entity_VehicleRecord": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/git_abanppc_com_farin-project_vehicle-records_domain_entity.VehicleRecord"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "git_abanppc_com_farin-project_vehicle-records_app_api_response.Response-swagger_EmptyObject": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/swagger.EmptyObject"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "git_abanppc_com_farin-project_vehicle-records_domain_entity.CitizenVehiclePhoto": {
            "type": "object",
            "properties": {
                "CitizenVehiclePhoto": {
                    "type": "string"
                },
                "CitizenVehiclePhotoArea": {
                    "type": "string"
                },
                "CitizenVehiclePhotoCaptureTime": {
                    "type": "integer"
                },
                "CitizenVehiclePlateCropPhoto": {
                    "type": "string"
                },
                "LPRVehicleCameraId": {
                    "type": "integer"
                },
                "OCRAccuracy": {
                    "type": "number"
                },
                "PhotoSequenceId": {
                    "type": "integer"
                },
                "RecordId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "integer"
                }
            }
        },
        "git_abanppc_com_farin-project_vehicle-records_domain_entity.VehicleRecord": {
            "type": "object",
            "properties": {
                "BackoffTime": {
                    "description": "unix timestamp backoff time",
                    "type": "integer"
                },
                "CitizenParkType": {
                    "type": "integer"
                },
                "CitizenPlateNumber": {
                    "type": "string"
                },
                "CitizenPlateNumberNumeric": {
                    "type": "integer"
                },
                "CitizenVehicleColor": {
                    "type": "integer"
                },
                "CitizenVehicleDegree": {
                    "type": "integer"
                },
                "CitizenVehicleDistance": {
                    "type": "integer"
                },
                "CitizenVehicleModel": {
                    "type": "string"
                },
                "CitizenVehiclePlateNumberColor": {
                    "type": "integer"
                },
                "CitizenVehiclePlateNumberType": {
                    "type": "integer"
                },
                "CitizenVehicleType": {
                    "type": "integer"
                },
                "CreatedAt": {
                    "type": "integer"
                },
                "CycleID": {
                    "type": "integer"
                },
                "IsCitizenVehicleDistorted": {
                    "type": "boolean"
                },
                "IsCitizenVehiclePlateNumberVisible": {
                    "type": "boolean"
                },
                "IsJunction": {
                    "type": "boolean"
                },
                "LPRSystemAppId": {
                    "type": "string"
                },
                "LPRSystemAppVersion": {
                    "type": "string"
                },
                "LPRSystemId": {
                    "type": "string"
                },
                "LPRVehicleGPSError": {
                    "type": "integer"
                },
                "LPRVehicleGPSLatitude": {
                    "type": "number"
                },
                "LPRVehicleGPSLongitude": {
                    "type": "number"
                },
                "LPRVehicleGPSSpeed": {
                    "type": "number"
                },
                "LPRVehicleId": {
                    "type": "string"
                },
                "LPRVehicleIsGPSSignalValid": {
                    "type": "boolean"
                },
                "LPRVehicleRTKError": {
                    "type": "integer"
                },
                "LPRVehicleRTKLatitude": {
                    "type": "number"
                },
                "LPRVehicleRTKLongitude": {
                    "type": "number"
                },
                "OCRAccuracy": {
                    "type": "number"
                },
                "ParkingLotId": {
                    "type": "integer"
                },
                "PlateDetectionID": {
                    "type": "integer"
                },
                "RecordId": {
                    "type": "string"
                },
                "RecordSendTime": {
                    "type": "integer"
                },
                "RecordStoreTime": {
                    "type": "integer"
                },
                "Retries": {
                    "type": "integer"
                },
                "RingId": {
                    "type": "integer"
                },
                "RoadCode": {
                    "description": "streetCode",
                    "type": "integer"
                },
                "SegmentId": {
                    "type": "integer"
                },
                "Sent": {
                    "type": "boolean"
                },
                "ShamsiTime": {
                    "type": "string"
                },
                "StreetId": {
                    "type": "integer"
                },
                "TehranRequestID": {
                    "type": "string"
                },
                "UpdatedAt": {
                    "type": "integer"
                },
                "UserId": {
                    "type": "string"
                },
                "VehiclePhotos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/git_abanppc_com_farin-project_vehicle-records_domain_entity.CitizenVehiclePhoto"
                    }
                }
            }
        },
        "swagger.EmptyObject": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
