apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: kube-prometheus-stack-pg-state
    release: kube-prometheus-stack
  name: kube-prometheus-stack-pg-state
  namespace: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: pg-state

  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 15s
      scrapeTimeout: 14s
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - uat