// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/v1/datasource/rule/rule.go
//
// Generated by this command:
//
//	mockgen -source=./internal/v1/datasource/rule/rule.go -destination=./mock/datasource/rule.go
//

// Package mock_rule is a generated GoMock package.
package mock_rule

import (
	reflect "reflect"

	entity "application/internal/v1/entity/rule"
	gomock "go.uber.org/mock/gomock"
)

// MockRule is a mock of Rule interface.
type MockRule struct {
	ctrl     *gomock.Controller
	recorder *MockRuleMockRecorder
}

// MockRuleMockRecorder is the mock recorder for MockRule.
type MockRuleMockRecorder struct {
	mock *MockRule
}

// NewMockRule creates a new mock instance.
func NewMockRule(ctrl *gomock.Controller) *MockRule {
	mock := &MockRule{ctrl: ctrl}
	mock.recorder = &MockRuleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRule) EXPECT() *MockRuleMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockRule) GetAll() ([]*entity.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]*entity.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRuleMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRule)(nil).GetAll))
}
