// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/internal/http/oapi"
	"context"
	"github.com/swaggest/openapi-go/openapi3"
	"log/slog"
)

// Injectors from wire.go:

func wireApp(ctx context.Context, logger *slog.Logger, r *openapi3.Reflector) (*openapi3.Spec, error) {
	oapiOAPI := oapi.NewOAPI(r, logger)
	healthzOpenApi := oapi.NewHealthzOpenApi(logger, oapiOAPI)
	userOpenApi := oapi.NewUserOpenApi(logger)
	roleOpenApi := oapi.NewRoleOpenApi(logger)
	authOpenApi := oapi.NewAuthOpenApi(logger)
	vehicleOpenApi := oapi.NewVehicleOpenApi(logger)
	contractorOpenApi := oapi.NewContractorOpenApi(logger)
	ringOpenApi := oapi.NewRingOpenApi(logger)
	driverOpenApi := oapi.NewDriverOpenApi(logger)
	deviceOpenApi := oapi.NewDeviceOpenApi(logger)
	workCalendarOpenApi := oapi.NewWorkCalendarOpenApi(logger)
	cityOpenApi := oapi.NewCityOpenApi(logger)
	districtOpenApi := oapi.NewDistrictOpenApi(logger)
	spec := oapi.GetSpec(oapiOAPI, healthzOpenApi, userOpenApi, roleOpenApi, authOpenApi, vehicleOpenApi, contractorOpenApi, ringOpenApi, driverOpenApi, deviceOpenApi, workCalendarOpenApi, cityOpenApi, districtOpenApi)
	return spec, nil
}
