// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"application/config"
	"application/internal/biz/auth"
	"application/internal/biz/device"
	"application/internal/biz/healthz"
	"application/internal/biz/idp"
	"application/internal/datasource"
	http2 "application/internal/http"
	"application/internal/http/handler"
	"application/internal/repo"
	"application/internal/repo/healthz"
	"application/internal/repo/idp"
	"application/internal/repo/vehicle"
	"context"
	"github.com/swaggest/openapi-go/openapi3"
	"log/slog"
	"net/http"
)

// Injectors from wire.go:

func wireApp(ctx context.Context, cfg config.Config, logger *slog.Logger, oapi3r *openapi3.Reflector) (http.Handler, error) {
	oapi := handler.NewOAPI(oapi3r, logger)
	healthzRepoInterface := healthzrepo.NewHealthzDS(logger)
	healthzUseCaseInterface := healthzusecase.NewHealthzBiz(healthzRepoInterface, logger)
	healthzHandler := handler.NewMuxHealthzHandler(healthzUseCaseInterface, logger)
	datasourceDatasource := datasource.NewDataSource(cfg, logger)
	userRepositoryInterface := idprepo.NewUserRepo(logger, datasourceDatasource)
	userUseCaseInterface := idpbiz.NewUserUseCase(logger, userRepositoryInterface)
	idpHandler := handler.NewIDPHandler(logger, userUseCaseInterface)
	autUsecaseInterface := authbiz.NewAuthUsecase(logger, userUseCaseInterface, cfg)
	authHandler := handler.NewAuthHandler(logger, autUsecaseInterface)
	vehicleRepositoryInterface := vehicle.NewVehicleRepo(logger, datasourceDatasource)
	vehicleServiceInterface := device.NewVehicleService(logger, vehicleRepositoryInterface)
	vehicleHandler := handler.NewVehicleHandler(logger, vehicleServiceInterface)
	ringRepository := datasource.NewRingRepository()
	ringHandler := handler.NewRingHandler(logger, ringRepository)
	driverRepository := datasource.NewDriverRepository()
	driverHandler := handler.NewDriverHandler(logger, driverRepository)
	deviceRepository := repo.NewDeviceRepository()
	deviceHandler := handler.NewDeviceHandler(logger, deviceRepository)
	conteractorHandler := handler.NewConteractorHandler(logger)
	workCalendarRepository := repo.NewWorkCalendarRepository()
	workCalendarHandler := handler.NewWorkCalendarHandler(logger, workCalendarRepository)
	cityHandler := handler.NewCityHandler(logger)
	districtRepository := repo.NewDistrictRepository()
	districtHandler := handler.NewDistrictHandler(logger, districtRepository)
	v := handler.NewServiceList(healthzHandler, idpHandler, authHandler, vehicleHandler, ringHandler, driverHandler, deviceHandler, conteractorHandler, workCalendarHandler, cityHandler, districtHandler)
	httpHandler, err := http2.NewHTTPHandler(oapi3r, oapi, v...)
	if err != nil {
		return nil, err
	}
	return httpHandler, nil
}
