// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/v1/http/handler/handler.go
//
// Generated by this command:
//
//	mockgen -source=./internal/v1/http/handler/handler.go -destination=./mock/handler/handler.go
//

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFuncHandler is a mock of FuncHandler interface.
type MockFuncHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFuncHandlerMockRecorder
}

// MockFuncHandlerMockRecorder is the mock recorder for MockFuncHandler.
type MockFuncHandlerMockRecorder struct {
	mock *MockFuncHandler
}

// NewMockFuncHandler creates a new mock instance.
func NewMockFuncHandler(ctrl *gomock.Controller) *MockFuncHandler {
	mock := &MockFuncHandler{ctrl: ctrl}
	mock.recorder = &MockFuncHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFuncHandler) EXPECT() *MockFuncHandlerMockRecorder {
	return m.recorder
}

// HandleFunc mocks base method.
func (m *MockFuncHandler) HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleFunc", pattern, handler)
}

// HandleFunc indicates an expected call of HandleFunc.
func (mr *MockFuncHandlerMockRecorder) HandleFunc(pattern, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFunc", reflect.TypeOf((*MockFuncHandler)(nil).HandleFunc), pattern, handler)
}
