// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"git.abanppc.com/farin-project/vehicle-records/app/api/controllers"
	"git.abanppc.com/farin-project/vehicle-records/app/api/routes"
	rabbit2 "git.abanppc.com/farin-project/vehicle-records/app/rabbit"
	"git.abanppc.com/farin-project/vehicle-records/app/rabbit/consumers"
	"git.abanppc.com/farin-project/vehicle-records/app/rabbit/handlers"
	"git.abanppc.com/farin-project/vehicle-records/domain/opentelemetry"
	"git.abanppc.com/farin-project/vehicle-records/domain/repository"
	"git.abanppc.com/farin-project/vehicle-records/domain/service"
	"git.abanppc.com/farin-project/vehicle-records/infrastructure/godotenv"
	"git.abanppc.com/farin-project/vehicle-records/infrastructure/gorm"
	"git.abanppc.com/farin-project/vehicle-records/infrastructure/rabbit"
	"github.com/mahdimehrabi/uploader/minio"
	"log/slog"
)

import (
	_ "git.abanppc.com/farin-project/vehicle-records/docs"
)

// Injectors from wire.go:

func wireApp(logger *slog.Logger, rabbit3 *rabbit.Rabbit, minio2 *minio.Minio, gorm *gormdb.GORMDB, ot *opentelemetry.OpenTelemetry) (*Boot, error) {
	vehicleRecordRepository := repository.NewVehicleRecordRepository(gorm)
	minIOFileRepository := minio.NewMinIOFileRepository(minio2)
	env := godotenv.NewEnv()
	citizenVehiclePhotoRepository := repository.NewCitizenVehiclePhotoRepository(gorm)
	tehranSiteRecordRepository := repository.NewTehranSiteRecordRepository(env, logger)
	vehicleRecordService := service.NewVehicleRecordService(logger, vehicleRecordRepository, minIOFileRepository, env, citizenVehiclePhotoRepository, tehranSiteRecordRepository, rabbit3, ot, minio2)
	eventVehicleRecord := handlers.NewEventVehicleRecord(logger, vehicleRecordService, ot)
	eventConsumer := consumers.NewEventConsumer(logger, env)
	retryConsumer := consumers.NewRetryConsumer(logger, env)
	v := rabbit2.Consumers(eventConsumer, retryConsumer)
	consumerRunner := rabbit.NewConsumerRunner(logger, v...)
	retry := handlers.NewRetry(logger, vehicleRecordService, ot)
	healthController := controller.NewHealthController(logger, rabbit3, minio2, gorm, eventConsumer)
	healthRouter := routes.NewHealthRouter(healthController)
	vehicleRecordController := controller.NewVehicleRecordController(vehicleRecordService)
	vehicleRecordRouter := routes.NewVehicleRecordRouter(vehicleRecordController)
	v2 := routes.CreateRouters(healthRouter, vehicleRecordRouter)
	boot := NewBoot(eventVehicleRecord, eventConsumer, rabbit3, consumerRunner, retryConsumer, retry, vehicleRecordService, env, logger, v2...)
	return boot, nil
}
