// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"farin/app/api/controllers"
	"farin/app/api/middleware"
	"farin/app/api/routes"
	"farin/app/api/validators"
	"farin/app/api/validators/gorm"
	rabbit2 "farin/app/rabbit"
	"farin/app/rabbit/consumers"
	"farin/app/rabbit/handlers"
	"farin/domain/repository"
	"farin/domain/service"
	"farin/infrastructure/godotenv"
	"farin/infrastructure/gorm"
	"farin/infrastructure/opentelemetry"
	"farin/infrastructure/rabbit"
	"github.com/mahdimehrabi/uploader/minio"
	"log/slog"
)

import (
	_ "farin/docs"
)

// Injectors from wire.go:

func wireApp(logger *slog.Logger, rabbit3 *rabbit.Rabbit, minio2 *minio.Minio, gorm2 *gormdb.GORMDB, ot *opentelemetry.OpenTelemetry) (*Boot, error) {
	uniqueValidator := gorm.NewUniqueValidator(gorm2)
	fkValidator := gorm.NewFkValidator(gorm2)
	timestampValidator := validators.NewTimestampValidator()
	fileValidator := validators.NewFileValidator(logger)
	validatorsValidators := validators.NewValidators(uniqueValidator, fkValidator, timestampValidator, fileValidator)
	vehicleRecordRepository := repository.NewVehicleRecordRepository(gorm2)
	minIOFileRepository := minio.NewMinIOFileRepository(minio2)
	env := godotenv.NewEnv()
	citizenVehiclePhotoRepository := repository.NewCitizenVehiclePhotoRepository(gorm2)
	eventRecordRabbitMQ := repository.NewEventRecordRabbitMQ(rabbit3, env)
	vehicleRecordService := service.NewVehicleRecordService(logger, vehicleRecordRepository, minIOFileRepository, env, citizenVehiclePhotoRepository, ot, eventRecordRabbitMQ)
	vehicleRecord := handlers.NewVehicleRecord(logger, vehicleRecordService, ot)
	eventConsumer := consumers.NewEventConsumer(logger, env)
	v := rabbit2.Consumers(eventConsumer)
	consumerRunner := rabbit.NewConsumerRunner(logger, v...)
	userRepository := repository.NewUserRepository(gorm2)
	driverRepository := repository.NewDriverRepository(gorm2)
	vehicleRepository := repository.NewVehicleRepository(gorm2)
	deviceRepository := repository.NewDeviceRepository(gorm2)
	driverAssignmentRepository := repository.NewDriverAssignmentRepository(gorm2)
	contractorRepository := repository.NewContractorRepository(gorm2)
	authService := service.NewAuthService(env, logger, userRepository, driverRepository, vehicleRepository, deviceRepository, driverAssignmentRepository, contractorRepository)
	userService := service.NewUserService(logger, userRepository, minIOFileRepository, env)
	authController := controller.NewAuthController(env, authService, userService, logger)
	authMiddleware := middleware.NewAuthMiddleware(logger, env, userRepository)
	adminMiddleware := middleware.NewAdminMiddleware(logger, env)
	authRouter := routes.NewAuthRouter(authController, authMiddleware, adminMiddleware)
	healthController := controller.NewHealthController(logger, rabbit3, minio2, gorm2, eventConsumer)
	healthRouter := routes.NewHealthRouter(healthController)
	userController := controller.NewUserController(logger, userService, env)
	contractRepository := repository.NewContractRepository(gorm2)
	contractService := service.NewContractService(logger, contractRepository, minIOFileRepository, env)
	contractController := controller.NewContractController(logger, contractService, env)
	contractorService := service.NewContractorService(logger, contractorRepository, minIOFileRepository, env)
	contractorController := controller.NewContractorController(logger, contractorService, env)
	driverService := service.NewDriverService(logger, driverRepository, minIOFileRepository, env)
	driverController := controller.NewDriverController(logger, driverService, env)
	vehicleService := service.NewVehicleService(logger, vehicleRepository, minIOFileRepository, env)
	vehicleController := controller.NewVehicleController(logger, vehicleService, env)
	deviceService := service.NewDeviceService(logger, deviceRepository, minIOFileRepository, env)
	deviceController := controller.NewDeviceController(logger, deviceService, env)
	roleRepository := repository.NewRoleRepository(gorm2)
	roleService := service.NewRoleService(logger, roleRepository, minIOFileRepository, env)
	roleController := controller.NewRoleController(logger, roleService)
	calenderRepository := repository.NewCalenderRepository(gorm2)
	calenderService := service.NewCalenderService(logger, calenderRepository, minIOFileRepository, env)
	calenderController := controller.NewCalenderController(logger, calenderService, env)
	ringRepository := repository.NewRingRepository(gorm2)
	ringService := service.NewRingService(logger, ringRepository, minIOFileRepository, env)
	ringController := controller.NewRingController(logger, ringService, env)
	driverAssignmentService := service.NewDriverAssignmentService(logger, driverAssignmentRepository, minIOFileRepository, env)
	driverAssignmentController := controller.NewDriverAssignmentController(logger, driverAssignmentService, env)
	userRouter := routes.NewUserRouter(userController, authMiddleware, contractController, contractorController, adminMiddleware, driverController, vehicleController, deviceController, roleController, calenderController, ringController, driverAssignmentController)
	v2 := routes.CreateRouters(authRouter, healthRouter, userRouter)
	boot := NewBoot(validatorsValidators, vehicleRecord, eventConsumer, consumerRunner, rabbit3, v2...)
	return boot, nil
}
