apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-gateway-proxy-config
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort