apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  # annotations:
  # argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: default
  source:
    repoURL: https://github.com/mr03k/parking-hub.git
    targetRevision: HEAD
    path: argocd-main/resources/infra/opentelemetry
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator-system
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: "*"
    kind: "*"
    managedFieldsManagers:
    - fabric8-kubernetes-client
