apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq-cluster-operator
    targetRevision: 4.3.18
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
