apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uat-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mr03k/parking-hub.git
    targetRevision: HEAD
    path: argocd-main/argo-apps/uat-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
