apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-management-k8s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://git.abanppc.com/farin-project/infra/argocd.git
    targetRevision: HEAD
    path: resources/infra/user-management
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
