apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-vehicle-record-second
  namespace: uat
spec:
  # ? use initdb for a fresh DB
  bootstrap:
    initdb:
      database: vehicle_records
      owner: aban
      encoding: UTF8
      localeCType: C
      localeCollate: C

  # ? REMOVE these if they exist in your file:
  # bootstrap:
  #   recovery:
  #     database: vehicle_records
  #     owner: aban
  #     secret:
  #       name: postgres-user-secret
  #     source: pg-vehicle-record
  #
  # externalClusters:
  #   - name: pg-vehicle-record
  #     barmanObjectStore:
  #       destinationPath: s3://db-backups
  #       endpointURL: https://z10.s3.cloud.ir
  #       ...etc...

  imageName: ghcr.io/cloudnative-pg/postgis:16-3.5-114
  instances: 1
  storage:
    size: 150Gi
    resizeInUseVolumes: true
  enablePDB: true
  enableSuperuserAccess: false
  managed:
    roles:
      - name: aban
        superuser: true
        # ... (keep the role bits as they are in your file)
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: pg-vehicle-record-second-nodeport
            spec:
              type: NodePort
          updateStrategy: patch
  # keep the monitoring, postgresql: parameters etc as in your file
